[app]
    env = "dev"
    service_name = "AI_CRM_001"
    host = "0.0.0.0"
    port = "8080"

[database]
    dialect = "postgres"
    host = "postgres"
    port = 5432
    username = "postgres"
    password = "postgres"
    ssl_mode = "disable"
    name = "crm"
    maxopenconns = 10
    maxidleconns = 5
    connmaxlifetime = 120 # in seconds
