FROM golang:1.24

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
  && rm -rf /var/lib/apt/lists/*

COPY go.mod go.sum ./
RUN go mod download

RUN go install github.com/air-verse/air@v1.61.5

COPY . .
RUN cp ./config/docker.toml ./config/default.toml

EXPOSE 8081

CMD ["air", "-c", ".air.toml"]
